### PR TITLE
Jupiter 10.9.0 ecdn

### PR DESCRIPTION
**Pull request by igorshevach**
Added kaltura-postinst dep to kaltura-media-server as requested.

### CODE REVIEW

**Comment by igorshevach** [comment]
I am bypassing the call to kaltura-base-config.sh by first checking for ecdn ini file existence

**Comment by jessp01** [comment]
- Add a changelog entry to the spec file
- Remove RC_FILE=/etc/kaltura.d/system.ini from the config script, your are overriding it anyhow a few lines later, plus, you will never have this file if you don't have the kaltura-base package, since /etc/kaltura.d/system.ini is a symlink to /opt/kaltura/app/configurations/system.ini

After making this two modifications - can be merged.

**Comment by igorshevach** [comment]
Do you want me to make another pull request to make sure I don't do anything against your will?

**Comment by jessp01** [comment]
You can just fix this one.

May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
connect.kaltura.com

**Pull request merged**
