### PR TITLE
Update install-kaltura-focal.md

### PR DESCRIPTION
**Pull request by horvan**
removed -curr fro,m the gpg-key wget command so that copy and paste works again

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @horvan,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by jessp01** [comment]
Hello @horvan ,

Thank you for your pull. However, ` http://installrepo.kaltura.org/repo/aptn/focal/kaltura-deb-curr-256.gpg.key` is in fact the correct key.
Can you please elaborate as to the problem?

**Comment by horvan** [comment]
It is simple the file mentioned in the tutorial is not in the repository right now.  Click below and take a look, please

http://installrepo.kaltura.org/repo/aptn/focal/kaltura-deb-curr-256.gpg.key

**Comment by jessp01** [comment]
Ah, yes, I understand now. Thanks:) That's a copy paste error, since for Xenial, the correct file is kaltura-deb-curr-256.gpg.key (historical reasons, etc).
Happy to merge as soon as you sign the CLA agreement (that's necessary so we can credit you for your contribution).

**Pull request merged**
