### PR TITLE
Added support for primary and secondary servers

### PR DESCRIPTION
**Pull request by kobimichaeli**
PLAT-2859#time 4h

### CODE REVIEW

**Comment by jessp01** [comment]
Hi Kobi,

Few notes:

  46 BROADCAST_TEMPLATE_FILE=$BASE_DIR/app/configurations/broadcast.template.ini
  47 BROADCAST_FILE=$BASE_DIR/app/configurations/broadcast.ini

Please use $APP_DIR. Its not THAT important but since we do have it...

  51 if [ -z $KALTURA_FULL_VIRTUAL_HOST_NAME ];

Please change to:
  51 if [ -z "$KALTURA_FULL_VIRTUAL_HOST_NAME" ];

To prevent a warning if the var is unset.
Same is true for:
63 if [ -z $PRIMARY_MEDIA_SERVER_HOST ]; then
  90 if [ -z $SECONDARY_MEDIA_SERVER_HOST ] ;
 104 elif [ $SECONDARY_MEDIA_SERVER_HOST == $PRIMARY_MEDIA_SERVER_HOST ];
117 [ -f $BROADCAST_FILE_TEMP ] && mv $BROADCAST_FILE_TEMP $TEMP_BROADCAST

Please also output messages with echo -e "${CYAN}..${NORMAL}" since this is our convention in the other scripts.

Thanks,

**Comment by DBezemer** [comment]
@kobimichaeli you are aware that the secondary server will only be loaded if you are specifying two DC configurations? By default it only matches the DC by name, so even when setting a secondary media server it will not be loaded by KMC configuration unless this is patched in the server repository

**Comment by tan-tan-kanarek** [comment]
That used to be true, but not anymore, see:
https://github.com/kaltura/server/commit/959e857b00f1be9c3b071f1d92bd4d376f2b3411

**Comment by kobimichaeli** [comment]
Changed according to the remarks made by Jess.

**Comment by jessp01** [comment]
hi Kobi, not seeing the changes.. did you push?

**Comment by jessp01** [comment]
@kobimichaeli - ping?
:)

**Pull request merged**
