### PR TITLE
replaced a file link with a conditional link

### PR DESCRIPTION
**Pull request by kobimichaeli**
PLAT-3482 #time 3h

### CODE REVIEW

**Comment by jessp01** [comment]
Hi Kobi,

Not sure about the scenario we're handling here... if the batch uses localhost as its service URL, we do not really need SSL cause all the communication is local and its just an overhead. If it uses remote then its irrelevant. Can you please explain the motive?

Thanks,

**Comment by kobimichaeli** [comment]
Hi,

Sure:
In a scenario in which everything is on the same machine there is no justification for SSL, however what is the case in a proper install (distributed deployment)? Shouldn’t the batch communicate with the API server in ssl?
If so, the apache should include only the ssl configuration if I understand correctly, but if it’s non-ssl, then a different fix is needed, meaning that the Kaltura.conf file needs to be configured as well, which I don’t think is happening at the moment.

I’ve attached the original mail I’ve sent for more info.

Thanks ☺            ,
Kobi M.

**Comment by jessp01** [comment]
Hi Kobi,

Sorry but still confused.. the change you are suggesting would mean the local batch machine would be running the api_v3 over SSL. If your batch is talking to another server and using IT as service_url, this configuration will never get into play because it will be talking to another Apache, not its own.. or am I missing something?

**Comment by jessp01** [comment]
Kobi and I spoke over emails but just to explain: the problem stems from the fact that after running kaltura-front-config, if SSL is selected, the contents of the non SSL config file still have place holders instead of actual values, causing Apache to refuse to load. This is fine since indeed, the file is not needed. Kobi's change simply symlinks the SSL config file in the event SSL was chosen in the front stage. For an all in 1, this is not needed since front config already achieved that but since the same script is also used in  the event of a cluster..

**Pull request merged**
