### PR TITLE
Removed duplicate

### PR DESCRIPTION
**Pull request by vadimtar**
Removed duplicate

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @vadimtar,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by jessp01** [comment]
Hi @vadimtar,

Please sign the CLA so I can merge.

**Comment by vadimtar** [comment]
Done

**Comment by jessp01** [comment]
Great, thanks.

**Pull request merged**
