### PR TITLE
Lynx 12.9.0 nginx dynamic modules

### PR DESCRIPTION
**Pull request by doubleshot**
Added nginx dynamic module support
Added AWS auth and Headers more modules as dynamic modules

### CODE REVIEW

**Comment by jessp01** [comment]
Hi @doubleshot, in regards to:
NGX_AWS_AUTH_URI="https://github.com/doubleshot/ngx_aws_auth/archive/$NGX_AWS_AUTH_VERSION.zip"

Any reason why we're not using the original repo [https://github.com/anomalizer/ngx_aws_auth]?

**Comment by doubleshot** [comment]
Hi @jessp01 Yes, since the maintainer has not created a tag yet with the dynamic module support, I had to create a tag myself on my fork. I've opened an issue with him to do so, but he has been absent. I "pinky swear" to keep my git repo active and will create a PR on his repo once he creates a formal release.

**Comment by jessp01** [comment]
Hi @doubleshot,
In that case, I suggest you clone the repo under the Kaltura org instead. Do let me know once done and I'll release a new kaltura-nginx package with the additional modules built as DSOs.

**Comment by jessp01** [comment]
https://github.com/kaltura/ngx_aws_auth/releases/tag/2.0.1 was created and will be used instead.

**Pull request merged**
